#!/usr/bin/expect -f
set timeout -1
spawn npx -y firebase-tools@latest init firestore --project pg-manager-10ff5

expect "What file should be used for Firestore Rules?"
send "firestore.rules\r"

expect "File firestore.rules already exists. Do you want to overwrite it with the Firestore Rules from the Firebase Console?"
send "n\r"

expect "What file should be used for Firestore indexes?"
send "firestore.indexes.json\r"

expect eof
